### ISSUE TITLE
[Umbrella] Rewamping the library

### ISSUE THREAD

**Issue by ig-sinicyn** [rsdn/CodeJam#152]
I'm going to spend some time in order to revive the project and release a new major version.

The primary goals are the following (issues/PRs to be linked).

- [ ] Remove dead code (CodeJam.PerfTests). There's git history so we may revive it at any moment
- [ ] move all build artifacts (`bin` and `obj` dirs) into root `.artifacts` directory. The change is going to happen with .net 8 anyways, so I'll just speed it up :)
- [ ] Update multitargeting subsystem. I'm going to make a new approach and use reusable MsBuild .targets / .props files. As a side bonus I do expect to have much more readable csproj files
- [ ] Update Appveyor pipelines. As it turns out the scripts may be simplified a lot. Also, I've managed to add target framework annotations to the test results (this helps a lot if build fails).
- [ ] Remove unused dependencies (looks like we do not need ComponentModel.DataAnnotations dependency except for some enum helpers).

As a preview, there's [experimental repo](https://github.com/ig-sinicyn/CodeJam.Exp) with proofcode for points 2-4. Things to note:
* There's how [project with multitargeting](https://github.com/ig-sinicyn/CodeJam.Exp/blob/master/src/CodeJam.Light/CodeJam.Light.csproj) looks like
* The props for the project is autogenerated, shims to be used are selected [in the template file](https://github.com/ig-sinicyn/CodeJam.Exp/blob/master/build/Props/CodeJam.Multitargeting.tt).
* To proof that multitargeting is working as expected, there's a sample project that checks [all targeting features](https://github.com/ig-sinicyn/CodeJam.Exp/blob/master/examples/CodeJam.MinimalTargeting.Example/TargetingFeatures.cs) to be used in CJ library.
* [Test results](https://ci.appveyor.com/project/ig-sinicyn/codejam-exp/builds/47836208/tests) are annotated with the target framework (check the Assembly name column).

FYI @andrewvk @NN--- . If needed, we can make a call and improve the roadmap.

**Comment by NN---** [comment]
It seems like Theraot is not so maintained.
So there is some missing functionality thee, the coverage for new .NET features is not as good as it could be.
Tried to contact the maintainer but didn't have any luck.

**Comment by ig-sinicyn** [comment]
Yeah, I've managed to remove dependency on Theraot from most target frameworks except for net35 and net40.
<img width="342" alt="image" src="https://github.com/rsdn/CodeJam/assets/11225241/2b1cf159-bd42-41c8-8774-58e0b92e3d50">

**Comment by NN---** [comment]
Ah. Great.
There is a modern solution for new features using source generators for .NET Standard 2.0 and above.

**Comment by NN---** [comment]
https://www.meziantou.net/polyfills-in-dotnet-to-ease-multi-targeting.htm


Here the list.
Yeah T4 is nice but Source Generators are better integrated today.

**Comment by NN---** [comment]
https://github.com/Sergio0694/PolySharp
